export default [
  'Associate Business Analyst',
  'Business Analyst',
  'Senior Business Analyst',
  'Staff Business Analyst',
  'Principal Business Analyst',
  'Senior Principal Business Analyst',
  'Data Analyst I',
  'Data Analyst II',
  'Data Analyst III',
  'Senior Data Analyst',
  'Staff Data Analyst',
  'Principal Data Engineer',
  'Data Scientist I',
  'Data Scientist II',
  'Data Scientist III',
  'Senior Data Scientist',
  'Staff Data Scientist',
  'Principal Data Scientist',
  'Mobile Engineer I',
  'Mobile Engineer II',
  'Mobile Engineer III',
  'Senior Mobile Engineer',
  'Staff Mobile Engineer',
  'Principal Mobile Engineer',
  'Associate Product Manager',
  'Product Manager',
  'Senior Product Manager',
  'Staff Product Manager',
  'Principal Product Manager',
  'Senior Principal Product Manager',
  'Project Manager',
  'Senior Project Manager',
  'Staff Project Manager',
  'Principal Project Manager',
  'Senior Principal Project Manager',
  'QA Software Engineer I',
  'QA Software Engineer II',
  'QA Software Engineer III',
  'Senior QA Software Engineer',
  'Staff QA Software Engineer',
  'Principal QA Software Engineer',
  'Security Engineer I',
  'Security Engineer II',
  'Security Engineer III',
  'Senior Security Engineer',
  'Staff Security Engineer',
  'Principal Security Engineer',
  'Site Reliability Engineer I',
  'Site Reliability Engineer II',
  'Site Reliability Engineer III',
  'Senior Site Reliability Engineer',
  'Staff Site Reliability Engineer',
  'Principal Site Reliability Engineer',
  'Software Engineer I',
  'Software Engineer II',
  'Software Engineer III',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Software Engineer',
  'Technical Writer I',
  'Technical Writer II',
  'Technical Writer III',
  'Senior Technical Writer',
  'Staff Technical Writer',
  'Principal Technical Writer',
  'Associate UX Designer',
  'UX Designer',
  'Senior UX Designer',
  'Lead UX Designer',
  'Principal UX Designer',
  'Senior Principal UX Designer',
]
